FROM node:lts
WORKDIR /var/app

COPY package*.json ./
RUN npm install
COPY ./src ./src
COPY ./prod ./prod
RUN npm run build
COPY ./src/prodServiceWorker.js ./prod/dist/serviceWorker.js

ENV PORT 80

ENTRYPOINT [ "npm", "start"]