services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build:
      context: ./api
      ## Change this to Dockerfile.prod to use the production server
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./api/src:/var/app/src
    environment:
      - PORT=80
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend
      ## Change this to Dockerfile.prod to use the production server
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    environment:
      - PORT=80
    volumes:
      - "./frontend/src:/var/app/src"
    
    
  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecylce outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"
    env_file:
      - .env
    